-- duracionlinea.sql — la duración de una línea de herramienta (migración
-- 005-duracion-linea-herramienta).
--
-- Hasta ahora la línea cerrada decía la marca y la medida del resultado («✓
-- LEER [ruta] · 70 líneas»), pero no cuánto tardó: quien espera no puede
-- distinguir una búsqueda de tres segundos de un `go test` de dos minutos.
-- Esta columna guarda esa duración, en milisegundos.
--
-- Es aditiva y solo añade una columna: no crea tabla, no crea índice y no
-- toca filas. Las líneas ya guardadas quedan en NULL —«no se midió»— y se
-- pintan sin tiempo; no se rellena un tiempo inventado para tapar el hueco.
--
-- Sin CHECK: el valor lo valida el código, y así la migración no depende del
-- soporte de CHECK en ALTER TABLE (MIGRATIONS.md §4).
ALTER TABLE chat_evento ADD COLUMN duration_ms INTEGER;
